CREATE TABLE member (
ID INT NOT NULL PRIMARY KEY DEFAULT '0',
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
HANDLE VARCHAR(255) NOT NULL UNIQUE KEY DEFAULT '',
EMAIL VARCHAR(255) NOT NULL DEFAULT ''
) ;
